### ISSUE TITLE
Philosopher dies too late

### ISSUE THREAD

**Issue by UmutSogukpinar** [MustafaBulbul0/Philosophers#1]
**Title**  
[BUG] Philosopher dies too late in time_to_die checks for cases “4 300 200 200 5” and “3 500 200 200 5”

**Description**  
In the specified test cases, a philosopher should be marked as “died” exactly at `time_to_die` milliseconds after last meal or start, but the implementation reports death significantly later:

- **Case A:** `./philo 4 300 200 200 5` → expected death at ~300 ms, actual at ~400 ms  
- **Case B:** `./philo 3 500 200 200 5` → expected death at ~500 ms, actual at ~600 ms (observed)

This timing discrepancy causes mandatory test failures for death timing.

**Comment by MustafaBulbul0** [comment]
These problems have been resolved. Thank you for the feedback.

**Comment by UmutSogukpinar** [comment]
Hi, thanks for the update.

However, I suggest reconsidering the resolution, as the issue might still persist under certain timing conditions. Based on further observations, the death is still not detected accurately at the expected time in edge cases.
